dist: bionic
language: generic
before_script:
- wget https://download.qemu.org/qemu-4.1.0.tar.xz
- tar xvJf qemu-4.1.0.tar.xz
- cd qemu-4.1.0
- ./configure --target-list=arm-softmmu
- make -j$(nproc)
- make install
script:
- qemu-system-x86_64 --version
